spring:
  cloud:
    openfeign:
      client:
        config:
          krakenflex-api:
            defaultRequestHeaders:
              x-api-key: ${API_KEY:EltgJ5G8m44IzwE6UN2Y4B4NjPW77Zk6FJK3lL23}

api:
  krakenflex:
    url: ${KRAKENFLEX_API_URL:https://api.krakenflex.systems/interview-tests-mock-api/v1}

siteId: ${SITE_ID:norwich-pear-tree}
filteredOutageTime: ${FILTERED_OUTAGE_TIME:2022-01-01T00:00:00.000Z}